# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'caclulator_Vlad_Derkach.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(380, 412)
        Dialog.setStyleSheet("QDialog{\n"
"background: #b3b3b3;\n"
"\n"
"}")
        self.lable_output = QtWidgets.QLabel(Dialog)
        self.lable_output.setGeometry(QtCore.QRect(0, 0, 371, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lable_output.sizePolicy().hasHeightForWidth())
        self.lable_output.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        self.lable_output.setFont(font)
        self.lable_output.setStyleSheet("QLabel\n"
"{\n"
" qproperty-alignment: \'AlignVCenter | AlignRight\';\n"
" back-ground:#b3b3b3\n"
"\n"
"}\n"
"")
        self.lable_output.setObjectName("lable_output")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 60, 381, 351))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.qwe = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.qwe.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.qwe.setContentsMargins(0, 0, 0, 0)
        self.qwe.setSpacing(0)
        self.qwe.setObjectName("qwe")
        self.pushButton_dot = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_dot.sizePolicy().hasHeightForWidth())
        self.pushButton_dot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_dot.setFont(font)
        self.pushButton_dot.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid;\n"
"    background-color: #b3b3b3\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #d9d9d9\n"
"}R")
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.qwe.addWidget(self.pushButton_dot, 6, 3, 1, 1)
        self.pushButton_zero = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_zero.sizePolicy().hasHeightForWidth())
        self.pushButton_zero.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_zero.setFont(font)
        self.pushButton_zero.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid;\n"
"    background-color: #b3b3b3\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #d9d9d9\n"
"}R")
        self.pushButton_zero.setObjectName("pushButton_zero")
        self.qwe.addWidget(self.pushButton_zero, 6, 2, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_clear.sizePolicy().hasHeightForWidth())
        self.pushButton_clear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid;\n"
"    background-color: #b3b3b3\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #d9d9d9\n"
"}R")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.qwe.addWidget(self.pushButton_clear, 0, 0, 1, 1)
        self.pushButton_divided = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_divided.sizePolicy().hasHeightForWidth())
        self.pushButton_divided.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_divided.setFont(font)
        self.pushButton_divided.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid;\n"
"    background-color: #b3b3b3\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #d9d9d9\n"
"}R")
        self.pushButton_divided.setObjectName("pushButton_divided")
        self.qwe.addWidget(self.pushButton_divided, 6, 4, 1, 1)
        self.pushButton_six = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_six.sizePolicy().hasHeightForWidth())
        self.pushButton_six.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_six.setFont(font)
        self.pushButton_six.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid;\n"
"    background-color: #b3b3b3\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #d9d9d9\n"
"}R")
        self.pushButton_six.setObjectName("pushButton_six")
        self.qwe.addWidget(self.pushButton_six, 2, 3, 1, 1)
        self.pushButton_plus_minus = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_plus_minus.sizePolicy().hasHeightForWidth())
        self.pushButton_plus_minus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_plus_minus.setFont(font)
        self.pushButton_plus_minus.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid;\n"
"    background-color: #b3b3b3\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #d9d9d9\n"
"}R")
        self.pushButton_plus_minus.setObjectName("pushButton_plus_minus")
        self.qwe.addWidget(self.pushButton_plus_minus, 0, 3, 1, 1)
        self.pushButton_equals = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_equals.sizePolicy().hasHeightForWidth())
        self.pushButton_equals.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_equals.setFont(font)
        self.pushButton_equals.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid;\n"
"    background-color: #b3b3b3\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #d9d9d9\n"
"}R")
        self.pushButton_equals.setObjectName("pushButton_equals")
        self.qwe.addWidget(self.pushButton_equals, 6, 0, 1, 1)
        self.pushButton_five = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_five.sizePolicy().hasHeightForWidth())
        self.pushButton_five.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_five.setFont(font)
        self.pushButton_five.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid;\n"
"    background-color: #b3b3b3\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #d9d9d9\n"
"}R")
        self.pushButton_five.setObjectName("pushButton_five")
        self.qwe.addWidget(self.pushButton_five, 2, 2, 1, 1)
        self.pushButton_minus = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_minus.sizePolicy().hasHeightForWidth())
        self.pushButton_minus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_minus.setFont(font)
        self.pushButton_minus.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid;\n"
"    background-color: #b3b3b3\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #d9d9d9\n"
"}R")
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.qwe.addWidget(self.pushButton_minus, 1, 4, 1, 1)
        self.pushButton_del = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_del.sizePolicy().hasHeightForWidth())
        self.pushButton_del.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_del.setFont(font)
        self.pushButton_del.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid;\n"
"    background-color: #b3b3b3\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #d9d9d9\n"
"}R")
        self.pushButton_del.setObjectName("pushButton_del")
        self.qwe.addWidget(self.pushButton_del, 0, 2, 1, 1)
        self.pushButton_four = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_four.sizePolicy().hasHeightForWidth())
        self.pushButton_four.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_four.setFont(font)
        self.pushButton_four.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid;\n"
"    background-color: #b3b3b3\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #d9d9d9\n"
"}R")
        self.pushButton_four.setObjectName("pushButton_four")
        self.qwe.addWidget(self.pushButton_four, 2, 0, 1, 1)
        self.pushButton_percent = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_percent.sizePolicy().hasHeightForWidth())
        self.pushButton_percent.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_percent.setFont(font)
        self.pushButton_percent.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid;\n"
"    background-color: #b3b3b3\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #d9d9d9\n"
"}R")
        self.pushButton_percent.setObjectName("pushButton_percent")
        self.qwe.addWidget(self.pushButton_percent, 0, 4, 1, 1)
        self.pushButton_plus = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_plus.sizePolicy().hasHeightForWidth())
        self.pushButton_plus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_plus.setFont(font)
        self.pushButton_plus.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid;\n"
"    background-color: #b3b3b3\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #d9d9d9\n"
"}R")
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.qwe.addWidget(self.pushButton_plus, 2, 4, 1, 1)
        self.pushButton_seven = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_seven.sizePolicy().hasHeightForWidth())
        self.pushButton_seven.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_seven.setFont(font)
        self.pushButton_seven.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid;\n"
"    background-color: #b3b3b3\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #d9d9d9\n"
"}R")
        self.pushButton_seven.setObjectName("pushButton_seven")
        self.qwe.addWidget(self.pushButton_seven, 3, 0, 1, 1)
        self.pushButton_one = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_one.sizePolicy().hasHeightForWidth())
        self.pushButton_one.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_one.setFont(font)
        self.pushButton_one.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid;\n"
"    background-color: #b3b3b3\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #d9d9d9\n"
"}R")
        self.pushButton_one.setObjectName("pushButton_one")
        self.qwe.addWidget(self.pushButton_one, 1, 0, 1, 1)
        self.pushButton_eight = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_eight.sizePolicy().hasHeightForWidth())
        self.pushButton_eight.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_eight.setFont(font)
        self.pushButton_eight.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid;\n"
"    background-color: #b3b3b3\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #d9d9d9\n"
"}R")
        self.pushButton_eight.setObjectName("pushButton_eight")
        self.qwe.addWidget(self.pushButton_eight, 3, 2, 1, 1)
        self.pushButton_nine = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_nine.sizePolicy().hasHeightForWidth())
        self.pushButton_nine.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_nine.setFont(font)
        self.pushButton_nine.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid;\n"
"    background-color: #b3b3b3\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #d9d9d9\n"
"}R")
        self.pushButton_nine.setObjectName("pushButton_nine")
        self.qwe.addWidget(self.pushButton_nine, 3, 3, 1, 1)
        self.pushButton_two = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_two.sizePolicy().hasHeightForWidth())
        self.pushButton_two.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_two.setFont(font)
        self.pushButton_two.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid;\n"
"    background-color: #b3b3b3\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #d9d9d9\n"
"}R")
        self.pushButton_two.setObjectName("pushButton_two")
        self.qwe.addWidget(self.pushButton_two, 1, 2, 1, 1)
        self.pushButton_three = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_three.sizePolicy().hasHeightForWidth())
        self.pushButton_three.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_three.setFont(font)
        self.pushButton_three.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid;\n"
"    background-color: #b3b3b3\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #d9d9d9\n"
"}R")
        self.pushButton_three.setObjectName("pushButton_three")
        self.qwe.addWidget(self.pushButton_three, 1, 3, 1, 1)
        self.pushButton_multiply = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_multiply.sizePolicy().hasHeightForWidth())
        self.pushButton_multiply.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_multiply.setFont(font)
        self.pushButton_multiply.setStyleSheet("QPushButton\n"
"{\n"
"    border: 0px solid;\n"
"    background-color: #b3b3b3\n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #d9d9d9\n"
"}R")
        self.pushButton_multiply.setObjectName("pushButton_multiply")
        self.qwe.addWidget(self.pushButton_multiply, 3, 4, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lable_output.setText(_translate("Dialog", "0"))
        self.pushButton_dot.setText(_translate("Dialog", "."))
        self.pushButton_zero.setText(_translate("Dialog", "0"))
        self.pushButton_clear.setText(_translate("Dialog", "AC"))
        self.pushButton_divided.setText(_translate("Dialog", "/"))
        self.pushButton_six.setText(_translate("Dialog", "6"))
        self.pushButton_plus_minus.setText(_translate("Dialog", "+/-"))
        self.pushButton_equals.setText(_translate("Dialog", "="))
        self.pushButton_five.setText(_translate("Dialog", "5"))
        self.pushButton_minus.setText(_translate("Dialog", "−"))
        self.pushButton_del.setText(_translate("Dialog", "Del"))
        self.pushButton_four.setText(_translate("Dialog", "4"))
        self.pushButton_percent.setText(_translate("Dialog", "%"))
        self.pushButton_plus.setText(_translate("Dialog", "+"))
        self.pushButton_seven.setText(_translate("Dialog", "7"))
        self.pushButton_one.setText(_translate("Dialog", "1"))
        self.pushButton_eight.setText(_translate("Dialog", "8"))
        self.pushButton_nine.setText(_translate("Dialog", "9"))
        self.pushButton_two.setText(_translate("Dialog", "2"))
        self.pushButton_three.setText(_translate("Dialog", "3"))
        self.pushButton_multiply.setText(_translate("Dialog", "x"))



